### ISSUE TITLE
unable to start homebirdge

### ISSUE THREAD

**Issue by alanl228** [bartdorsey/homebridge-blinkcameras#1]
Hi,

Thanks for setting this up for us to be able to arm/disarm our blink cameras system. I am new to homebridge and really enjoy this plug-in. It was working great up until couple weeks ago and I am no longer able to leave the blink cameras running as accessories in config.json. It will simply freeze up the homebridge when launch and give me the following error

[10/22/2017, 12:21:16 AM] [Indoor] Error
    at Request.request.post [as _callback] (/usr/lib/node_modules/homebridge-blinkcameras/node_modules/node-blink-security/lib/blink.js:298:27)
    at Request.self.callback (/usr/lib/node_modules/homebridge-blinkcameras/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

I tried to reinstall my homebridge, all plug-in and even reinstall my raspbain. But I am still not able to simply arm/disarm my cameras. Do you mind point me to the right direction on this issue please?

Thanks,
Alan

**Comment by bartdorsey** [comment]
Yes, this started happening to my homebridge as well. My guess is that Blink has changed their API in some way. I haven't had time to dig into it and figure it out yet. For now I've just taken my blink config out of my home bridge. I'll also be looking into better error handling so this logs an error and doesn't break the entire homebridge daemon next time.

**Comment by bartdorsey** [comment]
I think maybe this might have resolved itself, I decided to go work on this today and when I setup my Homebridge and re-added my blink camera Homebridge starts now. I'm thinking maybe one of the underlying libraries I'm using fixed the problem. So I would recommend uninstalling and reinstalling my module, which will pull in new dependencies.

**Comment by alanl228** [comment]
Tried it earlier as suggested and indeed the control is back. Thank you very much!
