### ISSUE TITLE
Homebridge stops working after installing the update

### ISSUE THREAD

**Issue by MasterofKungfu9999** [bartdorsey/homebridge-blinkcameras#13]
Hi,

Homebridge is shutting down after installing the update:

[Homebridge] [5/14/2020, 08:47:17] Error: The requested platform "BlinkSecurityPlatform" was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/@hoobs/hoobs/lib/bridge/api.js:132:19)
    at Server._loadPlatforms (/usr/local/lib/node_modules/@hoobs/hoobs/lib/bridge/server.js:289:47)
    at Server.run (/usr/local/lib/node_modules/@hoobs/hoobs/lib/bridge/server.js:93:14)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/lib/bridge/cli.js:74:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/lib/bridge/bin/homebridge:27:59)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11[Homebridge] [5/14/2020, 08:47:17] Got SIGTERM, shutting down Homebridge...

**Comment by erickribeiro** [comment]
I had to change the platform to "BlinkCameras". Also, don't forget to add the new required parameters for 2-factor authentication. Example:

        {
            "platform": "BlinkCameras",
            "name": "Blink System",
            "username": "user@example.com",
            "password": "secret password",
            "deviceId": "unique device id, can be anything",
            "deviceName": "homebridge",
            "discovery": true
        }

**Comment by MasterofKungfu9999** [comment]
That's it. Thanks!
