### ISSUE TITLE
BlinkException [Error]: Can't retrieve system status

### ISSUE THREAD

**Issue by monteroman** [bartdorsey/homebridge-blinkcameras#18]
Hi there.
When my Blink system initializes, I get the following error (running on homebridge-blinkcameras 1.0.2):

[5/14/2020, 2:34:16 PM] Loaded plugin: homebridge-blinkcameras
[5/14/2020, 2:34:16 PM] Registering platform 'homebridge-blinkcameras.BlinkCameras'
[5/14/2020, 2:34:16 PM] ---
[5/14/2020, 2:34:17 PM] [Blink System] Initializing BlinkCameras platform...
[5/14/2020, 2:34:17 PM] [Blink System] Init
[5/14/2020, 2:34:17 PM] [Blink System] Authenticating with Blink API as (account hidden)
[5/14/2020, 2:34:17 PM] [Blink System] Finished Launching
[5/14/2020, 2:34:17 PM] [Blink System] Discovering Cameras
[5/14/2020, 2:34:17 PM] [Blink System] Inside Lock
[5/14/2020, 2:34:18 PM] [Blink System] BlinkException [Error]: Can't retrieve system status
    at Request._callback (/usr/lib/node_modules/homebridge-blinkcameras/node_modules/node-blink-security/lib/blink.js:456:25)
    at self.callback (/usr/lib/node_modules/homebridge-blinkcameras/node_modules/request/request.js:185:22)
    at Request.emit (events.js:223:5)
    at Request.onRequestError (/usr/lib/node_modules/homebridge-blinkcameras/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:223:5)
    at TLSSocket.socketErrorListener (_http_client.js:415:9)
    at TLSSocket.emit (events.js:223:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
-----------

It should be known that I have 2 sync modules.

Thanks!

**Comment by Venger2005** [comment]
I also have two sync modules and have managed to get them both authenticated. I remember receiving 2 emails requesting to authenticate devices (I’m assuming by devices they mean sync modules), so did you also receive w emails and did you authenticate both?

**Comment by monteroman** [comment]
Yes.  They are both authorized, but the cameras don't initialize for me.

**Comment by monteroman** [comment]
I just tried again with uninstalling the module, then reinstalling the module and putting in a new deviceId string.   I got the 2 emails and authorized, then restarted Homebridge once more and the error came back.

**Comment by monteroman** [comment]
So with some more digging and experimenting, I changed the deviceId again and it did send me 2 emails to authorize, but never sent me the 2FA email code and the plugin did not hold up to wait for 2FA.

**Comment by monteroman** [comment]
One more note - so this is Homebridge running under Unraid and when the instance starts up, it won't hold up waiting for input for the 2FA code.   It keeps moving on startup and then after getting the 2 emails and authorizing, I get no 3rd with the 2FA code and then this happens:

5/14/2020, 3:35:12 PM] [Blink System] BlinkAuthenticationException [Error]: Authentication problem: verification timeout
    at Request._callback (/usr/lib/node_modules/homebridge-blinkcameras/node_modules/node-blink-security/lib/blink.js:396:48)
    at Request.self.callback (/usr/lib/node_modules/homebridge-blinkcameras/node_modules/request/request.js:185:22)
    at Request.emit (events.js:223:5)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:223:5)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:312:28)
    at IncomingMessage.emit (events.js:228:7)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)

Subsequent restarts cause the error listed in my initial issue above.

**Comment by bartdorsey** [comment]
Closing this and tracking this here now https://github.com/bartdorsey/homebridge-blinkcameras/issues/22
