### ISSUE TITLE
Error: Can't retrieve system summary

### ISSUE THREAD

**Issue by mokrol** [bartdorsey/homebridge-blinkcameras#2]
I have been using this plugin for a few months and as of this week I started getting this error:

Error: Can't retrieve system summary
    at Request.request [as _callback] (/usr/lib/node_modules/homebridge-blinkcameras/node_modules/node-blink-security/lib/blink.js:96:18)
    at self.callback (/usr/lib/node_modules/homebridge-blinkcameras/node_modules/request/request.js:186:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/usr/lib/node_modules/homebridge-blinkcameras/node_modules/request/request.js:878:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)

Any thoughts on how to correct?

**Comment by mokrol** [comment]
Ping

**Comment by monteroman** [comment]
I had the same issue and stopped using the plugin and went to the blink-security-platform plugin, but it had its own set of issues unfortunately.   It would be really great if someone could get this working again.

**Comment by mokrol** [comment]
@bartdorsey - Do you no longer support this? Are we all alone out here...? :-)

**Comment by bartdorsey** [comment]
@mokrol I just haven't had time lately to devote to this, I think there's a fork of this that has gotten more attention, I actually don't use this plugin in my own homebridge setup currently.  If I have some time I'll try to look into what all has changed with the blink API. On the other hand, I've been wanting to switch to a different camera system that natively supports homekit and isn't owned by Amazon ☹️

**Comment by bartdorsey** [comment]
Here's the fork I was referring too https://github.com/jasmas/homebridge-platform-blink-security

**Comment by bartdorsey** [comment]
@mokrol I worked yesterday on a pretty major rewrite of this module, so keep watching the github for when I finally get it working.

**Comment by mokrol** [comment]
@bartdorsey - Thank you, sir! Really appreciate your work on this. I'll keep an eye out for sure.

**Comment by MasterofKungfu9999** [comment]
I have this Issue with the latest version. Can you tell me if it is fixed?

**Comment by mokrol** [comment]
I had to uninstall and reinstall and that corrected the issue for me.

**Comment by mokrol** [comment]
Sorry, misread the thread. This was also corrected for me.
