### ISSUE TITLE
Error: Can't retrieve system status

### ISSUE THREAD

**Issue by ImhotepDE** [bartdorsey/homebridge-blinkcameras#21]
After installation and successful authentication, the camera status is no longer displayed.

```
[Blink System] Error: Can't retrieve system status
    at Request.request [as _callback] (/usr/local/lib/node_modules/homebridge-blinkcameras/node_modules/node-blink-security/lib/blink.js:463:25)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-blinkcameras/node_modules/request/request.js:185:22)
    at Request.emit (events.js:188:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:188:13)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:276:13)
    at IncomingMessage.emit (events.js:193:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
```

Somebody help me?

**Comment by ImhotepDE** [comment]
after about one hour, the error occurs. Before that, there are no problems. If I re-initialize the plugin via the config it takes about one hour.

**Comment by bartdorsey** [comment]
It's possible this is just the blink API sometimes not returning the system status, or the plugin could be timing out trying to talk to the blink API. Unfortunately the module I use to talk to the API doesn't give me the reason the status couldn't be retrieved.

**Comment by ImhotepDE** [comment]
Something's wrong with the plugin. I just received an email from Blink Support and my account has been deactivated.

```
Hello,

My name is xxxxx and I am with the Blink team. While doing a routine server audit, your account was flagged and subsequently disabled due to unsupported scripts or apps running on your system. The only automation that is permitted for use with the Blink system is through Alexa and/or IFTTT. Please disable these scripts or apps and reach back out to me so that I can re-enable your account. 

Best,

xxxxx

Blink Technical Support
```

**Comment by Venger2005** [comment]
[I’m also experiencing the same problem here](https://github.com/bartdorsey/homebridge-blinkcameras/issues/8#issuecomment-633202505)

**Comment by amiantos** [comment]
> The only automation that is permitted for use with the Blink system is through Alexa and/or IFTTT.

I love how we paid for these cameras but now Amazon is trying to force us into their idea of how they should be used. When companies get bought out, it always ends up ruining the product eventually. First they keep trying to push their Next Door competitor on us in the app and now this.

**Comment by bartdorsey** [comment]
Closing and tracking this here https://github.com/bartdorsey/homebridge-blinkcameras/issues/22
