### ISSUE TITLE
Error: Can'r Retrive System Status

### ISSUE THREAD

**Issue by lynis311** [bartdorsey/homebridge-blinkcameras#22]
2FA emails get sent just fine and I click the allow button but am now plagued with the following message every minute or so.

[5/20/2020, 13:15:32] [Blink System] Discovering Cameras
[5/20/2020, 13:15:32] [Blink System] Inside Lock
[5/20/2020, 13:15:32] [Blink System] BlinkException [Error]: Can't retrieve system status
    at Request._callback (/usr/local/lib/node_modules/homebridge-blinkcameras/node_modules/node-blink-security/lib/blink.js:456:25)
    at self.callback (/usr/local/lib/node_modules/homebridge-blinkcameras/node_modules/request/request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.onRequestError (/usr/local/lib/node_modules/homebridge-blinkcameras/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:310:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:310:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by mtressl** [comment]
Same problem here, but started today in the morning.

```
[5/22/2020, 11:57:25 AM] [Blink Home Security] Couldn't retrieve camera status
[5/22/2020, 11:57:25 AM] [Blink Home Security] BlinkException [Error]: Can't retrieve system summary
    at Request._callback (/homebridge/node_modules/homebridge-blinkcameras/node_modules/node-blink-security/lib/blink.js:107:27)
    at Request.self.callback (/homebridge/node_modules/homebridge-blinkcameras/node_modules/request/request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.<anonymous> (/homebridge/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:310:20)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:416:28)
    at IncomingMessage.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[5/22/2020, 11:57:25 AM] [Blink Home Security] Couldn't retrieve summary status
[5/22/2020, 11:57:25 AM] [Blink Home Security] BlinkException [Error]: Can't retrieve system summary
    at Request._callback (/homebridge/node_modules/homebridge-blinkcameras/node_modules/node-blink-security/lib/blink.js:107:27)
    at Request.self.callback (/homebridge/node_modules/homebridge-blinkcameras/node_modules/request/request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.<anonymous> (/homebridge/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:310:20)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:416:28)
    at IncomingMessage.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[5/22/2020, 11:57:25 AM] [Blink Home Security] Couldn't retrieve camera status
[5/22/2020, 11:57:25 AM] [Blink Home Security] BlinkException [Error]: Can't retrieve system summary
    at Request._callback (/homebridge/node_modules/homebridge-blinkcameras/node_modules/node-blink-security/lib/blink.js:107:27)
    at Request.self.callback (/homebridge/node_modules/homebridge-blinkcameras/node_modules/request/request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.<anonymous> (/homebridge/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:310:20)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:416:28)
    at IncomingMessage.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[5/22/2020, 11:57:25 AM] [Blink Home Security] Couldn't retrieve camera status
[5/22/2020, 11:57:25 AM] [Blink Home Security] BlinkException [Error]: Can't retrieve system summary
    at Request._callback (/homebridge/node_modules/homebridge-blinkcameras/node_modules/node-blink-security/lib/blink.js:107:27)
    at Request.self.callback (/homebridge/node_modules/homebridge-blinkcameras/node_modules/request/request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.<anonymous> (/homebridge/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:310:20)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:416:28)
    at IncomingMessage.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[5/22/2020, 11:57:35 AM] [Blink Home Security] BlinkException [Error]: Can't arm the network: 82082
    at Request._callback (/homebridge/node_modules/homebridge-blinkcameras/node_modules/node-blink-security/lib/blink.js:253:27)
    at Request.self.callback (/homebridge/node_modules/homebridge-blinkcameras/node_modules/request/request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.<anonymous> (/homebridge/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:310:20)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:416:28)
    at IncomingMessage.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by ImhotepDE** [comment]
I have the problem too and something else happened, see also [Ticket](https://github.com/bartdorsey/homebridge-blinkcameras/issues/21) 

You should disable the plugin, otherwise the account will be deactivated.


Something's wrong with the plugin. I just received an email from Blink Support and my account has been deactivated.

```
Hello,

My name is xxxxx and I am with the Blink team. While doing a routine server audit, your account was flagged and subsequently disabled due to unsupported scripts or apps running on your system. The only automation that is permitted for use with the Blink system is through Alexa and/or IFTTT. Please disable these scripts or apps and reach back out to me so that I can re-enable your account. 

Best,

xxxxx

Blink Technical Support
```

**Comment by bartdorsey** [comment]
Can you try setting discovery to false in your config file?

**Comment by mtressl** [comment]
From my side, discovery was set to false resulting in the logs posted above.

**Comment by bartdorsey** [comment]
Okay thanks... I'm in the process of adding debug logging to the node-blink-security module so I can get better debug logs about what blink is sending back when this happens.

**Comment by ethempekin** [comment]
Is this resolved?

**Comment by monteroman** [comment]
So this may be a new wrinkle to the same bug.   

1. Go through the process of setting up the plugin from scratch and create a new location so it registers the 2 zones from my Blink account.

2. Restart, and I get the can't auth issue.

3. Take out the Blink configuration from the config.json and restart.

4. Put the config back in and restart.

5.  The Blink plugin initializes fine and shows my cameras and zones! 

6. Restart Homebridge again, it's gone again with this error:

[7/12/2020, 11:32:10 AM] [Blink System] Error authenticating with blink API BlinkException [Error]: Can't retrieve system status
    at Request._callback (/usr/lib/node_modules/homebridge-blinkcameras/node_modules/node-blink-security/lib/blink.js:460:25)
    at Request.self.callback (/usr/lib/node_modules/homebridge-blinkcameras/node_modules/request/request.js:185:22)
    at Request.emit (events.js:223:5)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:223:5)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:312:28)
    at IncomingMessage.emit (events.js:228:7)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)

7.  Take out the plugin from the config and restart.
8.  Put the config back in and restart - the cameras and zone modules are back!

I'm running Homebridge under an Unraid docker.

Maybe that will help resolve this....
