### ISSUE TITLE
New error and Homebridge becomes unresponsive in Home.app

### ISSUE THREAD

**Issue by mtressl** [bartdorsey/homebridge-blinkcameras#27]
My Homebridge just became unresponsive in HomeKit with the following error:

```
BlinkException [Error]: Can't retrieve system summary
    at Request._callback (/homebridge/node_modules/homebridge-blinkcameras/node_modules/node-blink-security/lib/blink.js:107:27)
    at Request.self.callback (/homebridge/node_modules/homebridge-blinkcameras/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/homebridge/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

Config:
```
        {
            "platform": "BlinkCameras",
            "name": "Blink Home Security",
            "username": "REDACTED",
            "password": "REDACTED",
            "deviceId": "R-E-D-A-C-T-E-D",
            "deviceName": "REDACTED",
            "discovery": false,
            "discoveryInterval": 7200
        },
```
Any idea why?

**Comment by bartdorsey** [comment]
This happened to me last night as well. I’m going to need to investigate.

**Comment by jojogrosso** [comment]
Just to add, I installed the plugin (first time) and I would have to reboot Homebridge once a day because all of the devices would show "No Response." I ended up removing the Blink plugin and I haven't had to reboot since. I'm guessing it's related to this issue being discussed here.

**Comment by amiantos** [comment]
Similarly this appears to only happen after 24h.

**Comment by ethempekin** [comment]
It makes homebridge unusable. I thought IFTTT or configurations in Blink app were intervening i so I removed them but error keeps coming. When out of home loosing all devices is annoying.

**Comment by bartdorsey** [comment]
Can the folks in this thread upgrade to the latest version. I've put in something that I hope will fix this.

**Comment by ethempekin** [comment]
Thank you. Trying this before i switch to homebridge from hoobs. I will let you know.

**Comment by amiantos** [comment]
I'll report back in 24 hours...

**Comment by ethempekin** [comment]
Just had an error:

`23/06/2020, 23:32:03 [Blink System] Couldn't retrieve camera status
23/06/2020, 23:32:03 [Blink System] BlinkException [Error]: Can't retrieve system summary
    at Request._callback (/home/hoobs/.hoobs/node_modules/node-blink-security/lib/blink.js:107:27)
    at Request.self.callback (/home/hoobs/.hoobs/node_modules/request/request.js:185:22)
    at Request.emit (events.js:223:5)
    at Request.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:223:5)
    at IncomingMessage.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:312:28)
    at IncomingMessage.emit (events.js:228:7)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
23/06/2020, 23:32:03 [Blink System] Couldn't retrieve camera status
23/06/2020, 23:32:03 [Blink System] BlinkException [Error]: Can't retrieve system summary
    at Request._callback (/home/hoobs/.hoobs/node_modules/node-blink-security/lib/blink.js:107:27)
    at Request.self.callback (/home/hoobs/.hoobs/node_modules/request/request.js:185:22)
    at Request.emit (events.js:223:5)
    at Request.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:223:5)
    at IncomingMessage.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:312:28)
    at IncomingMessage.emit (events.js:228:7)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
23/06/2020, 23:32:03 [Blink System] Couldn't retrieve camera status
23/06/2020, 23:32:03 [Blink System] BlinkException [Error]: Can't retrieve system summary
    at Request._callback (/home/hoobs/.hoobs/node_modules/node-blink-security/lib/blink.js:107:27)
    at Request.self.callback (/home/hoobs/.hoobs/node_modules/request/request.js:185:22)
    at Request.emit (events.js:223:5)
    at Request.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:223:5)
    at IncomingMessage.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:312:28)
    at IncomingMessage.emit (events.js:228:7)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) `

**Comment by bartdorsey** [comment]
Is your plugin working up until this happens? Mine's been running for more than 24 hours and it hasn't thrown this error again. It's also possible this error was just an intermittent failure trying to talk to blink's servers. I'm not sure if it's related to authentication.   After you got this error was your homebridge unresponsive in the Home app?

**Comment by ethempekin** [comment]
It was working smooth. I didn’t pay attention to home app and immediately restarted the server. Now let me monitor only the home app.

**Comment by amiantos** [comment]
At the 25 hour mark I got this error in the logs, but everything is still working as normal after that error (without needing to restart or anything). I'll just post my full log:

```
[6/22/2020, 6:36:36 PM] Homebridge is running on port 51862.
[6/22/2020, 6:36:44 PM] [Blink System] Found network 3337 S Durango
[6/22/2020, 6:36:44 PM] [Blink System] Found camera Living Room
[6/22/2020, 6:42:24 PM] [Blink System] [Living Room Camera] is disarmed
[6/22/2020, 6:42:24 PM] [Blink System] [3337 S Durango System] is disarmed
[6/22/2020, 6:52:19 PM] [Blink System] [Living Room Camera] is disarmed
[6/22/2020, 6:52:19 PM] [Blink System] [3337 S Durango System] is disarmed
[6/22/2020, 10:45:31 PM] [Blink System] [3337 S Durango System] is disarmed
[6/22/2020, 10:45:31 PM] [Blink System] [Living Room Camera] is disarmed
[6/22/2020, 10:56:10 PM] [Blink System] [3337 S Durango System] is disarmed
[6/22/2020, 10:56:11 PM] [Blink System] [Living Room Camera] is disarmed
[6/22/2020, 11:00:42 PM] [Blink System] [3337 S Durango System] is disarmed
[6/22/2020, 11:00:42 PM] [Blink System] [Living Room Camera] is disarmed
[6/22/2020, 11:57:28 PM] [Blink System] [3337 S Durango System] is disarmed
[6/22/2020, 11:57:28 PM] [Blink System] [Living Room Camera] is disarmed
[6/23/2020, 7:38:19 PM] [Blink System] Authenticating with Blink API as bradroot@me.com
[6/23/2020, 7:38:20 PM] [Blink System] Couldn't retrieve camera status
[6/23/2020, 7:38:20 PM] [Blink System] BlinkException [Error]: Can't retrieve system summary
    at Request._callback (/usr/local/lib/node_modules/homebridge-blinkcameras/node_modules/node-blink-security/lib/blink.js:107:27)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-blinkcameras/node_modules/request/request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:310:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:416:28)
    at IncomingMessage.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[6/23/2020, 7:38:21 PM] [Blink System] [3337 S Durango System] is disarmed
[6/23/2020, 7:38:46 PM] [Blink System] [Living Room Camera] is disarmed
[6/23/2020, 7:38:46 PM] [Blink System] [3337 S Durango System] is disarmed
[6/23/2020, 11:12:53 PM] [Blink System] [3337 S Durango System] is disarmed
... (and so on until present time)
```

**Comment by mtressl** [comment]
Same error appears here, system status and 2 of 3 cameras return an error:

```
[6/24/2020, 9:55:46 PM] [Blink Home Security] Authenticating with Blink API as <MY-USER>
[6/24/2020, 9:55:46 PM] [Blink Home Security] Couldn't retrieve summary status
[6/24/2020, 9:55:46 PM] [Blink Home Security] BlinkException [Error]: Can't retrieve system summary
    at Request._callback (/homebridge/node_modules/homebridge-blinkcameras/node_modules/node-blink-security/lib/blink.js:107:27)
    at Request.self.callback (/homebridge/node_modules/homebridge-blinkcameras/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/homebridge/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[6/24/2020, 9:55:46 PM] [Blink Home Security] Couldn't retrieve camera status
[6/24/2020, 9:55:46 PM] [Blink Home Security] BlinkException [Error]: Can't retrieve system summary
    at Request._callback (/homebridge/node_modules/homebridge-blinkcameras/node_modules/node-blink-security/lib/blink.js:107:27)
    at Request.self.callback (/homebridge/node_modules/homebridge-blinkcameras/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/homebridge/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[6/24/2020, 9:55:46 PM] [Blink Home Security] Couldn't retrieve camera status
[6/24/2020, 9:55:46 PM] [Blink Home Security] BlinkException [Error]: Can't retrieve system summary
    at Request._callback (/homebridge/node_modules/homebridge-blinkcameras/node_modules/node-blink-security/lib/blink.js:107:27)
    at Request.self.callback (/homebridge/node_modules/homebridge-blinkcameras/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/homebridge/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[6/24/2020, 9:55:47 PM] [Blink Home Security] [SUCCESSFUL CAM] is armed
```

**Comment by amiantos** [comment]
The error I posted above showed up again, but the system continues working normally after that, so it doesn't seem like a big problem at least for me.

**Comment by ethempekin** [comment]
I have this error but hoobs server still do not fail.

25/06/2020, 17:12:03 [Nest] API observe: error Error [ERR_HTTP2_STREAM_ERROR]: Stream closed with error code NGHTTP2_INTERNAL_ERROR
    at ClientHttp2Stream._destroy (internal/http2/core.js:2101:13)
    at ClientHttp2Stream.destroy (internal/streams/destroy.js:38:8)
    at ClientHttp2Stream.[kMaybeDestroy] (internal/http2/core.js:2117:12)
    at Http2Stream.onStreamClose (internal/http2/core.js:493:26) {
  code: 'ERR_HTTP2_STREAM_ERROR'

**Comment by mtressl** [comment]
> Same error appears here, system status and 2 of 3 cameras return an error:
> 
> ```
> [6/24/2020, 9:55:46 PM] [Blink Home Security] Authenticating with Blink API as <MY-USER>
> [6/24/2020, 9:55:46 PM] [Blink Home Security] Couldn't retrieve summary status
> [6/24/2020, 9:55:46 PM] [Blink Home Security] BlinkException [Error]: Can't retrieve system summary
>     at Request._callback (/homebridge/node_modules/homebridge-blinkcameras/node_modules/node-blink-security/lib/blink.js:107:27)
>     at Request.self.callback (/homebridge/node_modules/homebridge-blinkcameras/node_modules/request/request.js:185:22)
>     at Request.emit (events.js:315:20)
>     at Request.<anonymous> (/homebridge/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1154:10)
>     at Request.emit (events.js:315:20)
>     at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1076:12)
>     at Object.onceWrapper (events.js:421:28)
>     at IncomingMessage.emit (events.js:327:22)
>     at endReadableNT (_stream_readable.js:1221:12)
>     at processTicksAndRejections (internal/process/task_queues.js:84:21)
> [6/24/2020, 9:55:46 PM] [Blink Home Security] Couldn't retrieve camera status
> [6/24/2020, 9:55:46 PM] [Blink Home Security] BlinkException [Error]: Can't retrieve system summary
>     at Request._callback (/homebridge/node_modules/homebridge-blinkcameras/node_modules/node-blink-security/lib/blink.js:107:27)
>     at Request.self.callback (/homebridge/node_modules/homebridge-blinkcameras/node_modules/request/request.js:185:22)
>     at Request.emit (events.js:315:20)
>     at Request.<anonymous> (/homebridge/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1154:10)
>     at Request.emit (events.js:315:20)
>     at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1076:12)
>     at Object.onceWrapper (events.js:421:28)
>     at IncomingMessage.emit (events.js:327:22)
>     at endReadableNT (_stream_readable.js:1221:12)
>     at processTicksAndRejections (internal/process/task_queues.js:84:21)
> [6/24/2020, 9:55:46 PM] [Blink Home Security] Couldn't retrieve camera status
> [6/24/2020, 9:55:46 PM] [Blink Home Security] BlinkException [Error]: Can't retrieve system summary
>     at Request._callback (/homebridge/node_modules/homebridge-blinkcameras/node_modules/node-blink-security/lib/blink.js:107:27)
>     at Request.self.callback (/homebridge/node_modules/homebridge-blinkcameras/node_modules/request/request.js:185:22)
>     at Request.emit (events.js:315:20)
>     at Request.<anonymous> (/homebridge/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1154:10)
>     at Request.emit (events.js:315:20)
>     at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1076:12)
>     at Object.onceWrapper (events.js:421:28)
>     at IncomingMessage.emit (events.js:327:22)
>     at endReadableNT (_stream_readable.js:1221:12)
>     at processTicksAndRejections (internal/process/task_queues.js:84:21)
> [6/24/2020, 9:55:47 PM] [Blink Home Security] [SUCCESSFUL CAM] is armed
> ```

In my case Home App showed a couple of "not responding" devices.

**Comment by brianhackel** [comment]
> > Same error appears here, system status and 2 of 3 cameras return an error:
> 
> > 
> 
> > ```
> 
> > [6/24/2020, 9:55:46 PM] [Blink Home Security] Authenticating with Blink API as <MY-USER>
> 
> > [6/24/2020, 9:55:46 PM] [Blink Home Security] Couldn't retrieve summary status
> 
> > [6/24/2020, 9:55:46 PM] [Blink Home Security] BlinkException [Error]: Can't retrieve system summary
> 
> >     at Request._callback (/homebridge/node_modules/homebridge-blinkcameras/node_modules/node-blink-security/lib/blink.js:107:27)
> 
> >     at Request.self.callback (/homebridge/node_modules/homebridge-blinkcameras/node_modules/request/request.js:185:22)
> 
> >     at Request.emit (events.js:315:20)
> 
> >     at Request.<anonymous> (/homebridge/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1154:10)
> 
> >     at Request.emit (events.js:315:20)
> 
> >     at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1076:12)
> 
> >     at Object.onceWrapper (events.js:421:28)
> 
> >     at IncomingMessage.emit (events.js:327:22)
> 
> >     at endReadableNT (_stream_readable.js:1221:12)
> 
> >     at processTicksAndRejections (internal/process/task_queues.js:84:21)
> 
> > [6/24/2020, 9:55:46 PM] [Blink Home Security] Couldn't retrieve camera status
> 
> > [6/24/2020, 9:55:46 PM] [Blink Home Security] BlinkException [Error]: Can't retrieve system summary
> 
> >     at Request._callback (/homebridge/node_modules/homebridge-blinkcameras/node_modules/node-blink-security/lib/blink.js:107:27)
> 
> >     at Request.self.callback (/homebridge/node_modules/homebridge-blinkcameras/node_modules/request/request.js:185:22)
> 
> >     at Request.emit (events.js:315:20)
> 
> >     at Request.<anonymous> (/homebridge/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1154:10)
> 
> >     at Request.emit (events.js:315:20)
> 
> >     at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1076:12)
> 
> >     at Object.onceWrapper (events.js:421:28)
> 
> >     at IncomingMessage.emit (events.js:327:22)
> 
> >     at endReadableNT (_stream_readable.js:1221:12)
> 
> >     at processTicksAndRejections (internal/process/task_queues.js:84:21)
> 
> > [6/24/2020, 9:55:46 PM] [Blink Home Security] Couldn't retrieve camera status
> 
> > [6/24/2020, 9:55:46 PM] [Blink Home Security] BlinkException [Error]: Can't retrieve system summary
> 
> >     at Request._callback (/homebridge/node_modules/homebridge-blinkcameras/node_modules/node-blink-security/lib/blink.js:107:27)
> 
> >     at Request.self.callback (/homebridge/node_modules/homebridge-blinkcameras/node_modules/request/request.js:185:22)
> 
> >     at Request.emit (events.js:315:20)
> 
> >     at Request.<anonymous> (/homebridge/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1154:10)
> 
> >     at Request.emit (events.js:315:20)
> 
> >     at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1076:12)
> 
> >     at Object.onceWrapper (events.js:421:28)
> 
> >     at IncomingMessage.emit (events.js:327:22)
> 
> >     at endReadableNT (_stream_readable.js:1221:12)
> 
> >     at processTicksAndRejections (internal/process/task_queues.js:84:21)
> 
> > [6/24/2020, 9:55:47 PM] [Blink Home Security] [SUCCESSFUL CAM] is armed
> 
> > ```
> 
> 
> 
> In my case Home App showed a couple of "not responding" devices.

Same here. First time I open home app after the 24 hour window expires, all my homebridge devices show “not responding”. Closing and reopening the app refreshes them and they start responding again without any other intervention.

**Comment by ethempekin** [comment]
Already up time 2.5 days no real need to restart the homebridge server. Hope this continues.

**Comment by alekz44** [comment]
Works fine since I updated to the latest Version of your Plugin (Almosen a week)!
Thank you

**Comment by ethempekin** [comment]
Same here. With this latest development I still run my system on Hoobs.
