### ISSUE TITLE
2FA Instructions Unclear

### ISSUE THREAD

**Issue by sanchezl** [bartdorsey/homebridge-blinkcameras#28]
I am having trouble getting the plugin to authenticate with the blink API:

```
[6/17/2020, 3:36:33 PM] [Blink System] Error authenticating with blink API BlinkException [Error]: Can't retrieve system status
    at Request._callback (/usr/local/lib/node_modules/homebridge-blinkcameras/node_modules/node-blink-security/lib/blink.js:463:25)
    at self.callback (/usr/local/lib/node_modules/homebridge-blinkcameras/node_modules/request/request.js:185:22)
. . . 
```

> Due to two factor authentication being required for Blink login the first time you run homebridge after installing this plugin it will pause and wait for you to enter your two factor authentication code.

Where exactly am I entering this authentication code? I've been using homebridge running as a systemd service along with the config ui x web console. 

> You will receive two emails from Blink, one with the code and one to "Allow Device". Make sure you Allow Device before entering your two factor authentication code.

If I watch the homebridge logs when starting up with a new `deviceId` I see the pause starting up the blink plugin. I get an email "Allow Device" and I quickly click on it, but the plugin still fails to log in. I never see any mention of the two factor authentication code. Oddly enough, I eventually get a second email asking me to "Allow Device" I click on it and restart homebridge, but the plugin still fails to log in.

I'll also note that the "Allow Device" email states that the device name is `*IDEVICENAMEI*` even though I filled in `devicename` in the config.

**Comment by lynis311** [comment]
I am having this same issue.

[6/22/2020, 16:44:48] [Blink System] Error authenticating with blink API BlinkException [Error]: Can't retrieve system status
    at Request._callback (/usr/local/lib/node_modules/homebridge-blinkcameras/node_modules/node-blink-security/lib/blink.js:463:25)
    at self.callback (/usr/local/lib/node_modules/homebridge-blinkcameras/node_modules/request/request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.onRequestError (/usr/local/lib/node_modules/homebridge-blinkcameras/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:310:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:310:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by bartdorsey** [comment]
Can you upgrade to the latest version and see if that resolves this?

Also I'm pretty sure at this point you don't have to actually enter the 2 factor code to make this work, although I'm still trying to find out for sure from the author of node-blink-security.

**Comment by sanchezl** [comment]
I built a version of homebridge w/ http-debug module and I got this just before the BlinkException:

```
HTTPS REQUEST: ERROR EVENT
Trace: Error: certificate has expired
    at TLSSocket.onConnectSecure (_tls_wrap.js:1474:34)
    at TLSSocket.emit (events.js:310:20)
    at TLSSocket._finishInit (_tls_wrap.js:917:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:687:12) {
  code: 'CERT_HAS_EXPIRED'
}
    at ClientRequest.httpDebugErrorEvent (/home/sanchezl/Developer/homebridge/node_modules/http-debug/index.js:66:25)
    at ClientRequest.emit (events.js:322:22)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:310:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by sanchezl** [comment]
Using openssl directly confirms that some of the servers are returning expired ssl certs (only stdout shown below):
```sh-session
$ openssl s_client -showcerts -connect rest.u002.immedia-semi.com:443 </dev/null 
depth=2 C = GB, ST = Greater Manchester, L = Salford, O = COMODO CA Limited, CN = COMODO RSA Certification Authority
verify return:1
depth=1 C = GB, ST = Greater Manchester, L = Salford, O = COMODO CA Limited, CN = COMODO RSA Domain Validation Secure Server CA
verify return:1
depth=0 OU = Domain Control Validated, OU = EssentialSSL Wildcard, CN = *.u002.immedia-semi.com
verify error:num=10:certificate has expired
notAfter=May 29 23:59:59 2019 GMT
verify return:1
depth=0 OU = Domain Control Validated, OU = EssentialSSL Wildcard, CN = *.u002.immedia-semi.com
notAfter=May 29 23:59:59 2019 GMT
verify return:1
DONE
$
```

**Comment by sanchezl** [comment]
Here is an example of someone else running into this problem: https://github.com/home-assistant/core/issues/24221

**Comment by bartdorsey** [comment]
Sounds like we need to open a ticket with the node-blink-security package then. I can’t do anything about expired blink server certs.

**Comment by lynis311** [comment]
I have upgraded to the latest version (1.1.2) and it is still not working but it sounds like you guys have discovered another issue.  Thank you for taking time out of your day to address this btw I appreciate it.
