### ISSUE TITLE
Authentification problem 

### ISSUE THREAD

**Issue by SchneidoDUS** [bartdorsey/homebridge-blinkcameras#30]
New problem from today on. Any ideas?

   at process._tickCallback (internal/process/next_tick.js:114:19)
    at endReadableNT (_stream_readable.js:1101:12)
    at IncomingMessage.emit (events.js:185:15)
    at Object.onceWrapper (events.js:272:13)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1076:12)
    at Request.emit (events.js:180:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:180:13)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-blinkcameras/node_modules/request/request.js:185:22)
    at Request.request.post [as _callback] (/usr/local/lib/node_modules/homebridge-blinkcameras/node_modules/node-blink-security/lib/blink.js:403:48)
[2020-7-10 16:36:56] [Blink System] Error authenticating with blink API Error: Authentication problem: verification timeout

**Comment by bartdorsey** [comment]
I had this for a while, but I think blink's systems were down. After they came up we all started having a different error (they changed the API a bit) but version v1.1.4 which I just released should fix this.
