### ISSUE TITLE
v1.1.4 still not working for me

### ISSUE THREAD

**Issue by koweye** [bartdorsey/homebridge-blinkcameras#32]
this is my log ... timeout?

7/11/2020, 6:21:44 PM [No Blink] Error authenticating with blink API BlinkAuthenticationException [Error]: Authentication problem: verification timeout
    at Request._callback (/home/hoobs/.hoobs/node_modules/node-blink-security/lib/blink.js:400:48)
    at Request.self.callback (/home/hoobs/.hoobs/node_modules/request/request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:310:20)
    at IncomingMessage.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:416:28)
    at IncomingMessage.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by koweye** [comment]
at least it doesn't crash my entire HOOBS service so everything does work.

**Comment by koweye** [comment]
sorry my bad, i had an email saying i needed to verify device trying to connect. once i allowed it looks like it worked
