### ISSUE TITLE
Unable to authenticate with blink API. Timeout error

### ISSUE THREAD

**Issue by damonmarkjones** [bartdorsey/homebridge-blinkcameras#35]
Once the plugin is installed with the correct settings (see config below), upon restarting homebridge the authentication API call fails due to a timeout (see log output below). Due to the timeout I do not receive the 2 emails to progress with 2fa.

**Config**
`{
            "name": "Night",
            "username": "*******",
            "password": "*****",
            "deviceId": "id-1234",
            "deviceName": "name-1234",
            "platform": "BlinkCameras",
            "discovery": true,
            "discoveryInterval": 3600
        }`

**Log output**
<img width="1350" alt="Screenshot 2020-07-17 at 13 31 42" src="https://user-images.githubusercontent.com/16006664/87787387-74ff5800-c833-11ea-84db-cdd04510579e.png">

I have uninstalled/reinstalled the plugin and made sure all other plugins are up to date. Can you confirm if this is an issue?

**Comment by SchneidoDUS** [comment]
I have the same since today

**Comment by SchneidoDUS** [comment]
> I have the same since today

Update: works again. No idea about the problem.

**Comment by SidShetye** [comment]
I'm also seeing this issue since I installed this 2 days back. Not getting any login emails from blink for `homebridge-blinkcameras` logins but I am getting them when logging out/in from the Blink iOS app. Also double checked the username/password and HomeBridge and all plugins are up-to-date. The rest of my HomeBridge system works just fine.

**Comment by hunterpaul** [comment]
> I'm also seeing this issue since I installed this 2 days back. Not getting any login emails from blink for `homebridge-blinkcameras` logins but I am getting them when logging out/in from the Blink iOS app. Also double checked the username/password and HomeBridge and all plugins are up-to-date. The rest of my HomeBridge system works just fine.
> 
> ```
> [7/20/2020, 5:03:40 PM] [Blink System] Error authenticating with blink API BlinkAuthenticationException [Error]: Authentication problem: verification timeout
>     at Request._callback (/usr/lib/node_modules/homebridge-blinkcameras/node_modules/node-blink-security/lib/blink.js:400:48)
>     at Request.self.callback (/usr/lib/node_modules/homebridge-blinkcameras/node_modules/request/request.js:185:22)
>     at Request.emit (events.js:315:20)
>     at Request.<anonymous> (/usr/lib/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1154:10)
>     at Request.emit (events.js:315:20)
>     at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1076:12)
>     at Object.onceWrapper (events.js:421:28)
>     at IncomingMessage.emit (events.js:327:22)
>     at endReadableNT (_stream_readable.js:1221:12)
>     at processTicksAndRejections (internal/process/task_queues.js:84:21)
> ```

I'm seeing exactly the same issue. No emails being received

**Comment by crowston** [comment]
I have a different error, but the same end state and also no emails, so perhaps this will help to track it down?  

[7/26/2020, 11:35:56 AM] [Blink] Finished Launching
[7/26/2020, 11:35:56 AM] [Blink] Discovering Cameras
[7/26/2020, 11:35:56 AM] [Blink] Authenticating with Blink API as account@crowston.name
Making new blink client
[7/26/2020, 11:35:56 AM] TypeError: Cannot read property 'message' of undefined
    at Request.request.post [as _callback] (/usr/local/lib/node_modules/homebridge-blinkcameras/node_modules/node-blink-security/lib/blink.js:396:90)
    at self.callback (/usr/local/lib/node_modules/homebridge-blinkcameras/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.onRequestError (/usr/local/lib/node_modules/homebridge-blinkcameras/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:198:13)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at TLSSocket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[7/26/2020, 11:35:56 AM] Got SIGTERM, shutting down Homebridge...

**Comment by sebasbe91** [comment]
Same here
