### ISSUE TITLE
Authentication problem: An app update is required

### ISSUE THREAD

**Issue by zadigre** [bartdorsey/homebridge-blinkcameras#37]
up until today, my Blink plugin was working fine... but this afternoon is started to give me this error:
`
[7/30/2020, 2:25:30 PM] [Blink] Error authenticating with blink API BlinkAuthenticationException [Error]: Authentication problem: An app update is required
    at Request._callback (/usr/lib/node_modules/homebridge-blinkcameras/node_modules/node-blink-security/lib/blink.js:396:25)
    at Request.self.callback (/usr/lib/node_modules/homebridge-blinkcameras/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
`

and after a few tries, it gave me this error and my blink system and camera were remove from the accessories list and removed from homekit. 
`
[7/30/2020, 3:22:17 PM] [Blink] Error authenticating with blink API BlinkAuthenticationException [Error]: Authentication problem: An app update is required
    at Request._callback (/usr/lib/node_modules/homebridge-blinkcameras/node_modules/node-blink-security/lib/blink.js:396:25)
    at Request.self.callback (/usr/lib/node_modules/homebridge-blinkcameras/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
`

**Comment by SchneidoDUS** [comment]
Yes. Same problem

**Comment by rcoletti116** [comment]
Does it also make your other Homebridge accessories fail? Seems to be the case for me.

**Comment by SchneidoDUS** [comment]
> Does it also make your other Homebridge accessories fail? Seems to be the case for me.

No further problems with other devices. In my case Sonos

**Comment by zadigre** [comment]
> Does it also make your other Homebridge accessories fail? Seems to be the case for me.

all my other accessories are working fine.

**Comment by mtressl** [comment]
Same here:
`[7/30/2020, 10:46:08 PM] [Blink Home Security] BlinkException [Error]: Can't retrieve system summary`

**Comment by dundrcheek** [comment]
I have 11 cameras on 3 systems and when I get this same failure, all cameras are 'unregistered' and removed form homekit, which then removes them from the rooms I put them in and all automations or scenes they were a part of.  If I restart homebridge again, usually they come back but all of them are once again in the 'default room' and have to be moved and added to automations/scenes all over again.  LOVE the ability to arm/disarm individual cameras with automation, but with this issue, it makes it problematic because if a single camera is disarmed through this plugin, then even when the blink system is armed through the blink app or IFTTT or other means, that camera doesn't get armed again.

**Comment by ethempekin** [comment]
> I have 11 cameras on 3 systems and when I get this same failure, all cameras are 'unregistered' and removed form homekit, which then removes them from the rooms I put them in and all automations or scenes they were a part of. If I restart homebridge again, usually they come back but all of them are once again in the 'default room' and have to be moved and added to automations/scenes all over again. LOVE the ability to arm/disarm individual cameras with automation, but with this issue, it makes it problematic because if a single camera is disarmed through this plugin, then even when the blink system is armed through the blink app or IFTTT or other means, that camera doesn't get armed again.

I restarted the homebridge but they are not found.

**Comment by mtressl** [comment]
Every time these errors come up, I feel that Amazon /Blink do not want us to use the cams like this, which is a real bummer. At least then they could give more possibilities to the Apps or the IFTTT integration.

**Comment by yphoenix** [comment]
Happened to me overnight. Seems Blink changed the API (again)
[Blink System] Error authenticating with blink API Error: Authentication problem: An app update is required
    at Request.request.post [as _callback] (/opt/node/lib/node_modules/homebridge-blinkcameras/node_modules/node-blink-security/lib/blink.js:396:25)
    at Request.self.callback (/opt/node/lib/node_modules/homebridge-blinkcameras/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/opt/node/lib/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/opt/node/lib/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js

**Comment by koweye** [comment]
yup noticed this too. same error. please fix!!! did the last update break it?

**Comment by bartdorsey** [comment]
So I'm waiting for node-blink-security to update. This isn't working for me, it appears blink did change the API (again). 👎

**Comment by mdiskin** [comment]
same for me
 Authentication problem: An app update is required

**Comment by vdrover** [comment]
Same here.

**Comment by amiantos** [comment]
Really seems like Amazon wants me to throw out my blink camera and order something that has no association with them whatsoever.

**Comment by koweye** [comment]
yup, i will be dumping my blinks soon. they are so far behind the curb compared to other camera features. its like blink is amazon's ugly step child.

**Comment by yphoenix** [comment]
Any other battery only other brands you’d care to recommend with HomeKit / HoneBridge support? Key advantage for me has always been not needing to run power to the cameras. I have multiple outdoor ones and power wouldn’t be an option for most of them.

**Comment by koweye** [comment]
i've been looking at and testing the eufy cam. battery, and no cloud fees. i only have the $50 indoor 2K pan tilt for now just to test and so far its really good. and yes its homekit compatible. later i will probably replace my blink xt with the eufy cam 2k or 2k pro. little pricey but i'm done with blinks.

**Comment by yphoenix** [comment]
They look good, yes pricy compared to Blink XT2, but getting so fed up of Amazon messing around. I assume HomeKit Support is via HomeBridge as I see no mention of native support. Do they have a published API - which would be a good selling point to anybody in automation?

**Comment by ethempekin** [comment]
> So I'm waiting for node-blink-security to update. This isn't working for me, it appears blink did change the API (again). 👎

So we just have to wait, right? Your plugin was very helpful.

**Comment by yphoenix** [comment]
Yes we have to wait. Also the maintainer of node-blink-security no longer uses a blink system so we need others to fix things. I have something in progress but it is in a rough state at the moment. If I have time I maybe be able to clean it up in a couple of weeks time. Sorry, so little time at the moment for side projects.

**Comment by koweye** [comment]
> They look good, yes pricy compared to Blink XT2, but getting so fed up of Amazon messing around. I assume HomeKit Support is via HomeBridge as I see no mention of native support. Do they have a published API - which would be a good selling point to anybody in automation?

if you are asking if eufy supports homekit, yes it supports it out of the box, at least for the eufy cam 2k indoor and 2k pan and tilt and eufy cam 2 outdoor. it states it on their product page. so no need to have a bridge it supports homekit out of the box

**Comment by ethempekin** [comment]
> > They look good, yes pricy compared to Blink XT2, but getting so fed up of Amazon messing around. I assume HomeKit Support is via HomeBridge as I see no mention of native support. Do they have a published API - which would be a good selling point to anybody in automation?
> 
> if you are asking if eufy supports homekit, yes it supports it out of the box, at least for the eufy cam 2k indoor and 2k pan and tilt and eufy cam 2 outdoor. it states it on their product page. so no need to have a bridge it supports homekit out of the box

Guess you need to install and keep their app to make use of the Homekit.

**Comment by koweye** [comment]
yeah i'm still figuring that out. since i will not pay to have my recording in apple's homekit secure video, i only use the home app to view a live stream and for it to alert me if there is motion. but the recording are stored on the SD card on the camera and viewed from the eufy app. but if you don't mind paying for icloud storage then i think you could get rid of the eufy app.

**Comment by vdrover** [comment]
@bartdorsey @jasmas Any thoughts on if this package will be updated?

**Comment by erickribeiro** [comment]
I just wanted to send a big thank you to @bartdorsey for creating and maintaining this amazing plugin! When the plugin worked, I loved the ability to automate through Homekit which cameras needed to be turned on and off based on who was home, time of day, etc. Ability to disable individual cameras isn't available through IFTTT.

Unfortunately, it doesn't seem Blink is interested in supporting Homebridge. Between the repeated API breakages and threats to suspend customer accounts for daring to call a public internet-facing API endpoint from a script, one could even argue Blink is hostile to the idea.

Whatever the case may be, I'm moving on to a Reolink 24/7 NVR system, which can be integrated into Homekit via [/homebridge-camera-ffmpeg](https://www.npmjs.com/package/homebridge-camera-ffmpeg) to watch live video right from the Home app, and even receive motion notifications via [homebridge-smtp-motion](https://github.com/Sunoo/homebridge-smtp-motion) to trigger Homekit automations.

As far as my 5-camera Blink system, it was good fun while the relationship lasted, I guess.
It's now on Craigslist.

**Comment by SchneidoDUS** [comment]
There is a solution. Create a Webhook in IFTTT and use the IFTTT Homebridge plugin. Works excellent. For more details look under the issue with the topic „API failure“, or good old google.

**Comment by erickribeiro** [comment]
> There is a solution. Create a Webhook in IFTTT and use the IFTTT Homebridge plugin. Works excellent. For more details look under the issue with the topic „API failure“, or good old google.

IFTTT only supports turning on or off the entire system, not the individual cameras.

And by the way, IFTTT has restricted standard accounts to at most 3 applets now. If you want more applets, you need to pay for the Pro version.

**Comment by vdrover** [comment]
@bartdorsey @jasmas Any chance to teach us how to update this plugin so the community can help maintain it as blink changes?

**Comment by mdiskin** [comment]
Likely it's related to this [upstream dependency](https://github.com/madshall/node-blink-security/issues/57)

**Comment by yphoenix** [comment]
As Amazon / Blink keep changing their API and don't want any non-authorized access to it I'm probably going to move the IFTTT route also, which sucks but I'm fed up with Blink breaking things all the time and having to maintain / fix things as I don't have the bandwidth even if I really wanted.

**Comment by rcoletti116** [comment]
Only problem with IFTTT is now they charge you if you want more than 3 applets. As I don't need/want another $10/month subscription I won't be going down that road.

**Comment by yphoenix** [comment]
Yep. I'm grandfathered in at $1.99 a month (at least for now) and a heavy user anyway for other automation - like arm the blink system when everybody leaves the house (might be able to do that with HomeKit nowadays, but didn't used to be able to do it with a group of multiple people).

**Comment by mpkossen** [comment]
I've been doing some digging into this and there have been substantial changes to the Blink API. node-blink-security will have to be largely rewritten because it relies mostly on the deprecated '/network' calls and structure. This plugin relies heavily on that module, so as long as that module isn't rewritten/fixed this plugin will likely not work. Even if you get past authentication (which I have) it just does nothing because the underlying structures are gone.

Not a big JS fan, but I'm looking into what I can do (either write a replacement library or try to fix the current one). Unless someone else is already making the effort, in which case I'd be more than happy to help.

**Comment by rcoletti116** [comment]
I worked on this a little on my own system and got it barely working, but it’s wholly dead again.  
There is a fork of homebridge-blinkcameras I’ve been keeping up with. It’s a fork, but really looks like it’s being completely rewritten without node-blink-security. Keeping my fingers crossed.

**Comment by mpkossen** [comment]
Well for one thing, Blink did actually improve their API with all the authentication changes. It seems, or based on what I see I assume, authentication tokens are issues per device ID and hopefully per IP address. This makes authentication considerably more secure and doesn't require a username and password to be stored somewhere.

This is also where node-blink-security is "broken": it does a login request every time it loads the system to get the authentication token. (I'm not assigning blame, I believe it has evolved like this with all Blink's changes.) The whole point of authentication tokens is that you don't need to keep sending login requests. During my tests, once I get the token, I can keep doing requests using just that token. So, I'll need to figure out a way to store the token so it can be reused. This should result in considerably less requests, and for what it's worth speed things up. The only question mark I have is how Blink deals with token expiration. IIRC OAuth has a refresh system so you can keep getting new tokens. BlinkPy's implementation just does a new login requests once it gets an authentication failed, which should be better than what happens now anyway.

Anyway, been thinking about this and given homebridge-blinkcameras' needs I might make a new, drop-in replacement for node-blink-security and probably solve the authentication "issue" later. I've already got the basics so now it's just implementing API calls.

**Comment by rcoletti116** [comment]
@mpkossen here's the fork I was referring to if you wanted to combine efforts. https://github.com/colinbendell/homebridge-blinkcameras

**Comment by vdrover** [comment]
@rcoletti116 Is this fork going to be released as a separate plugin? If not, how are u using it currently?

**Comment by rcoletti116** [comment]
It's not been released yet and I'm not sure of the author's intentions. He has been on the Homebridge discord asking for input on feature requests to work in. 

I installed it manually myself (cloned files using GIT, installed dependencies using NPM) to test it out as I couldn't control my curiosity. Still early and has some bugs. I only mention it because I think it makes sense to collaborate on development efforts rather than have multiple parties go out and try to fix it different ways. Ultimately I think we all want a single functioning, well-maintained plugin.

**Comment by vdrover** [comment]
I could not agree more.

**Comment by vdrover** [comment]
https://github.com/colinbendell/homebridge-blink-for-home

**Comment by mpkossen** [comment]
It definitely looks like a very promising replacement of node-blink-security and homebridge-blinkcameras in one!

Considering his effort, I will limit mine to just getting this up and running with homebridge-blinkcameras for the time being. I've gotten as far as having systems and cameras listed, updated and arming/disarming systems. Cameras remain left as it seems their enable/disable API calls have been deprecated and I don't know if and with which commands they have been replaced.

Once I've got it all cleaned up I'll fix 2FA as well. I had come up with the same approach as colinbendell, using config to save the PIN to see if that verification request needs to be made.

So, should be able to have this by the weekend if life doesn't intervene.

**Comment by vdrover** [comment]
Please do post here to let us know.

**Comment by colinbendell** [comment]
howdy folks. I'll push to cut a release in the next few days. I've been dithering on a few refactoring and existential organization of concerns. That said, I did end up reverse engineering and getting the RSTP streams to work with liveview, so that should come as a follow on release.

**Comment by vdrover** [comment]
Let us know how u get on. Happy to test.

**Comment by colinbendell** [comment]
I’ve published a version of https://www.npmjs.com/package/homebridge-blink-for-home and welcome for some testing.

**Comment by crowston** [comment]
Thanks! It is working to log in and list the cameras. I'll post issues on the project's GitHub issue tracker.
