### ISSUE TITLE
API Failure

### ISSUE THREAD

**Issue by rexerito** [bartdorsey/homebridge-blinkcameras#38]
8/20/2020, 1:02:08 PM] [BLINKREX] Finished Launching
[8/20/2020, 1:02:08 PM] [BLINKREX] Discovering Cameras
[8/20/2020, 1:02:08 PM] [BLINKREX] Authenticating with Blink API as rexerito@mac.com
Making new blink client
[8/20/2020, 1:02:09 PM] [BLINKREX] Error authenticating with blink API BlinkAuthenticationException [Error]: Authentication problem: An app update is required
    at Request._callback (/usr/local/lib/node_modules/homebridge-blinkcameras/node_modules/node-blink-security/lib/blink.js:396:25)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-blinkcameras/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by rexerito** [comment]
t8/20/2020, 1:02:08 PM] [BLINKREX] Finished Launching
[8/20/2020, 1:02:08 PM] [BLINKREX] Discovering Cameras
[8/20/2020, 1:02:08 PM] [BLINKREX] Authenticating with Blink API as rexerito@mac.com
Making new blink client
[8/20/2020, 1:02:09 PM] [BLINKREX] Error authenticating with blink API BlinkAuthenticationException [Error]: Authentication problem: An app update is required
    at Request._callback (/usr/local/lib/node_modules/homebridge-blinkcameras/node_modules/node-blink-security/lib/blink.js:396:25)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-blinkcameras/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by derfx4** [comment]
@Sungamm  Would you be able to share how you created the Webhooks in IFTTT? I looked today and wasn’t clear on how to create a unique action

**Comment by Sungamm** [comment]
> @Sungamm  Would you be able to share how you created the Webhooks in IFTTT? I looked today and wasn’t clear on how to create a unique action

Good Morning derfx4,
I assume you cannot understood german? ;-) I will try my best but it will be hard for us both :-D

Create an account at IFTTT.com if you dont have already. Afterwards click on "create" , -> Trigger "this" and search for "webhook". Enter a name for the Webhook (example blink-on). Click on That and search for blink. I use blink (Europe) because I am from Germany. I assume "blink" only is for Asia and the States. Choose "arm blink" and save.

Create a second one and name it (blink-off) and choose disarm blink. 

Install the homebrige [IFTTT plugin](https://www.npmjs.com/package/homebridge-ifttt) create the config.json

`"platform": "IFTTT",

			"name": "IFTTT",

			"makerkey": "PUT KEY OF YOUR MAKER CHANNEL HERE",

			"accessories": [

				{

					"name": "Accessory 1",

					"buttons": [

						{

							"caption": "Blink Security",

							"triggerOn": "blink-on",

							"triggerOff": "blink-off`

To catch the "maker key" it was a little bit tricky for me. I used [this link](https://ifttt.com/maker_webhooks) for it. But it works only if you created the webhooks before. 

Good luck. Great thing, if you spend few minutes to create the webhooks, it works perfect and smoothly. But be aware, if you sent the webhook request via Homebridge its needs about 15 seconds to arm / disarm. You can controll this in the blink app itself.

**Comment by derfx4** [comment]
@Sungamm This is perfect and very clear!!! Got it up and running. Solved a months old problem!

**Comment by Sungamm** [comment]
> 
> 
> @Sungamm This is perfect and very clear!!! Got it up and running. Solved a months old problem!

Hi derfx4,

good to read. Thank you for your feedback. I am really impressed about the effort from bartdorsey, but with IFTTT its a easy and reliable solution. 

Have a good time.

**Comment by SchneidoDUS** [comment]
Great. Thanks for the solution. I am not a pro with Homebridge etc. But I got it running. Solved my problem and Blink Cam is in Hinebridge again.

**Comment by ethempekin** [comment]
> > @Sungamm  Would you be able to share how you created the Webhooks in IFTTT? I looked today and wasn’t clear on how to create a unique action
> 
> Good Morning derfx4,
> I assume you cannot understood german? ;-) I will try my best but it will be hard for us both :-D
> 
> Create an account at IFTTT.com if you dont have already. Afterwards click on "create" , -> Trigger "this" and search for "webhook". Enter a name for the Webhook (example blink-on). Click on "That" and search for blink. I use blink (Europe) because I am from Germany. I assume "blink" only is for Asia and the States. Choose "arm blink" and save.
> 
> Create a second one and name it (blink-off) and choose disarm blink.
> 
> Install the homebrige [IFTTT plugin](https://www.npmjs.com/package/homebridge-ifttt) create the config.json
> 
> `"platform": "IFTTT",
> 
> ```
> 		"name": "IFTTT",
> 
> 		"makerkey": "PUT KEY OF YOUR MAKER CHANNEL HERE",
> 
> 		"accessories": [
> 
> 			{
> 
> 				"name": "Accessory 1",
> 
> 				"buttons": [
> 
> 					{
> 
> 						"caption": "Blink Security",
> 
> 						"triggerOn": "blink-on",
> 
> 						"triggerOff": "blink-off`
> ```
> 
> To catch the "maker key" it was a little bit tricky for me. I used [this link](https://ifttt.com/maker_webhooks) for it. But it works only if you created the webhooks before.
> 
> Good luck. Great thing, if you spend few minutes to create the webhooks, it works perfect and smoothly. But be aware, if you sent the webhook request via Homebridge its needs about 15 seconds to arm / disarm. You can controll this in the blink app itself.

Oh great but it would be great if you help also with the config. I think it has errors in it. 
Also for the makers challenge do you copy the complete hyperlink from IFTTT?

**Comment by mehepiim** [comment]
Thanks for the idea, can finally use blink via homekit again.

**Comment by ethempekin** [comment]
> > @Sungamm  Would you be able to share how you created the Webhooks in IFTTT? I looked today and wasn’t clear on how to create a unique action
> 
> Good Morning derfx4,
> I assume you cannot understood german? ;-) I will try my best but it will be hard for us both :-D
> 
> Create an account at IFTTT.com if you dont have already. Afterwards click on "create" , -> Trigger "this" and search for "webhook". Enter a name for the Webhook (example blink-on). Click on "That" and search for blink. I use blink (Europe) because I am from Germany. I assume "blink" only is for Asia and the States. Choose "arm blink" and save.
> 
> Create a second one and name it (blink-off) and choose disarm blink.
> 
> Install the homebrige [IFTTT plugin](https://www.npmjs.com/package/homebridge-ifttt) create the config.json
> 
> `"platform": "IFTTT",
> 
> ```
> 		"name": "IFTTT",
> 
> 		"makerkey": "PUT KEY OF YOUR MAKER CHANNEL HERE",
> 
> 		"accessories": [
> 
> 			{
> 
> 				"name": "Accessory 1",
> 
> 				"buttons": [
> 
> 					{
> 
> 						"caption": "Blink Security",
> 
> 						"triggerOn": "blink-on",
> 
> 						"triggerOff": "blink-off`
> ```
> 
> To catch the "maker key" it was a little bit tricky for me. I used [this link](https://ifttt.com/maker_webhooks) for it. But it works only if you created the webhooks before.
> 
> Good luck. Great thing, if you spend few minutes to create the webhooks, it works perfect and smoothly. But be aware, if you sent the webhook request via Homebridge its needs about 15 seconds to arm / disarm. You can controll this in the blink app itself.

I am now having some problems with this. Blink is nit turning off with IFTTT.

**Comment by Sungamm** [comment]
> 
> 
> > > @Sungamm  Would you be able to share how you created the Webhooks in IFTTT? I looked today and wasn’t clear on how to create a unique action
> > 
Hi ethempekin,

you copied my "instruction". What do you need excatly? What kind of trouble do you have?

Do you have a IFTTT account? Did not found the webhook function? Problem with the  maker key?

create the accout at IFTTT
create one webhook "turn on"
create one webhook "turn off"
check and copy your maker key
installe the IFTTT plug-in into homebridge
copy or create the entry for the config.json
reboot
have fun :-)

I am a user only but I can try to help. But please let me know first which of the above steps did not work.

**Comment by ethempekin** [comment]
> > > > @Sungamm  Would you be able to share how you created the Webhooks in IFTTT? I looked today and wasn’t clear on how to create a unique action
> 
> Hi ethempekin,
> 
> you copied my "instruction". What do you need excatly? What kind of trouble do you have?
> 
> Do you have a IFTTT account? Did not found the webhook function? Problem with the maker key?
> 
> create the accout at IFTTT
> create one webhook "turn on"
> create one webhook "turn off"
> check and copy your maker key
> installe the IFTTT plug-in into homebridge
> copy or create the entry for the config.json
> reboot
> have fun :-)
> 
> I am a user only but I can try to help. But please let me know first which of the above steps did not work.
> 
> P.S.: Are you EU or NA user? I assume that is important for the BLINK connection.

Hi, I used your guide indeed to control Blinks (EU). Now I cannot toggle off. I check IFTTT there when I give a try (test) it doesn’t trigger it and no error pops up.

**Comment by Sungamm** [comment]
ok. that means
 
create the accout at IFTTT - done
create one webhook "turn on" - done
create one webhook "turn off" - done (check this one, please). There are a lot of THAT options for BLINK. choose the "turn off". If there more than one, try the next one please.

check and copy your maker key - done?
installe the IFTTT plug-in into homebridge -done?
copy or create the entry for the config.json - done? check the name and the "triggeroff" name. Both must be excact the same. Try simple wording, ala turnon, turnoff.

**Comment by ethempekin** [comment]
When I hit check now on IFTTT nothing happens for blink-off. It has been runned 338 times since september.... last run says February 23

**Comment by Sungamm** [comment]
Hmm.. ok. I just check it. For me its running perfect and quite fast. Therefore its not a general problem. 
Do you have the blink app on your mobile? 

Can you manual turn off the blink and activate via Apple Homekit. Does this work?
Can you manual turn on the blink and de-activate via Apple Homekit. Does this work?

If one action did not run, check at first the log at Homebridge. 

You are sure that you have choose the correct THAT option for turnoff?

**Comment by ethempekin** [comment]
I created a new one in IFTTT for blink-off.
Still not working. I can control with no issues on Blink app.
I doubt if this is related to homebridge. My version there is v.1.0.3. There seems to be some changes when I hit the settings. My config is very simple. See below. Homebridge itself is  1.1.7. No errors in the log though. 

 "platform": "IFTTT",
            "name": "IFTTT",
            "makerkey": "abcd",
            "accessories": [
                {
                    "name": "Accessory 1",
                    "buttons": [
                        {
                            "caption": "Blink Security",
                            "triggerOn": "blink-on",
                            "triggerOff": "blink-off"

**Comment by Sungamm** [comment]
Puh... sorry I have no idea anymore. I have the latest Homebridge (stable) but with for former versions no issues in the past.

Only idea is to delete the blink-off webhook and create new (with same name). Try that out. 

If this not running, its better to ask in the Homebridge Forum or IFTTT itself group. Or you give the bartdorsey plugin a chance again?

**Comment by ethempekin** [comment]
Re-creating IFTTT recipe solved my problem. Thanks
