### ISSUE TITLE
Error: Attempting to register a platform 'homebridge-platform-blink-security.BlinkSecurityPlatform' which has already been registered!

### ISSUE THREAD

**Issue by mokrol** [bartdorsey/homebridge-blinkcameras#5]
Just updated and I'm getting this error now:
```
Updated with more details:

Dec 18 08:28:17 raspberrypi homebridge[1100]: [12/18/2019, 8:28:17 AM] Loaded config.json with 4 accessories and 4 platforms.
Dec 18 08:28:17 raspberrypi homebridge[1100]: [12/18/2019, 8:28:17 AM] ---
Dec 18 08:28:18 raspberrypi homebridge[1100]: [12/18/2019, 8:28:18 AM] Loaded plugin: homebridge-blinkcameras
Dec 18 08:28:18 raspberrypi homebridge[1100]: homebridge API version: 2.4
Dec 18 08:28:18 raspberrypi homebridge[1100]: [12/18/2019, 8:28:18 AM] Registering platform 'homebridge-platform-blink-security.BlinkSecurityPlatform'
Dec 18 08:28:18 raspberrypi homebridge[1100]: [12/18/2019, 8:28:18 AM] ---
Dec 18 08:28:21 raspberrypi homebridge[1100]: [12/18/2019, 8:28:21 AM] Loaded plugin: homebridge-camera-ffmpeg
Dec 18 08:28:21 raspberrypi homebridge[1100]: [12/18/2019, 8:28:21 AM] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
Dec 18 08:28:21 raspberrypi homebridge[1100]: [12/18/2019, 8:28:21 AM] ---
Dec 18 08:28:22 raspberrypi homebridge[1100]: [12/18/2019, 8:28:22 AM] Loaded plugin: homebridge-chamberlain
Dec 18 08:28:22 raspberrypi homebridge[1100]: [12/18/2019, 8:28:22 AM] Registering accessory 'homebridge-chamberlain.Chamberlain'
Dec 18 08:28:22 raspberrypi homebridge[1100]: [12/18/2019, 8:28:22 AM] ---
Dec 18 08:28:22 raspberrypi homebridge[1100]: [12/18/2019, 8:28:22 AM] Loaded plugin: homebridge-config-ui-x
Dec 18 08:28:22 raspberrypi homebridge[1100]: [12/18/2019, 8:28:22 AM] Registering platform 'homebridge-config-ui-x.config'
Dec 18 08:28:22 raspberrypi homebridge[1100]: [12/18/2019, 8:28:22 AM] ---
Dec 18 08:28:23 raspberrypi homebridge[1100]: [12/18/2019, 8:28:23 AM] Loaded plugin: homebridge-kunalight
Dec 18 08:28:23 raspberrypi homebridge[1100]: [12/18/2019, 8:28:23 AM] Registering accessory 'homebridge-kunalight.Kuna'
Dec 18 08:28:23 raspberrypi homebridge[1100]: [12/18/2019, 8:28:23 AM] ---
Dec 18 08:28:24 raspberrypi homebridge[1100]: [12/18/2019, 8:28:24 AM] Loaded plugin: homebridge-orbit-bhyve
Dec 18 08:28:24 raspberrypi homebridge[1100]: [12/18/2019, 8:28:24 AM] Registering accessory 'homebridge-orbit-bhyve.OrbitBHyve'
Dec 18 08:28:24 raspberrypi homebridge[1100]: [12/18/2019, 8:28:24 AM] ---
Dec 18 08:28:25 raspberrypi homebridge[1100]: [12/18/2019, 8:28:25 AM] Loaded plugin: homebridge-platform-blink-security
Dec 18 08:28:25 raspberrypi homebridge[1100]: homebridge API version: 2.4
Dec 18 08:28:25 raspberrypi homebridge[1100]: /usr/local/lib/node_modules/homebridge/lib/api.js:150
Dec 18 08:28:25 raspberrypi homebridge[1100]:     throw new Error("Attempting to register a platform '" + fullName + "' which has already been registered!");
Dec 18 08:28:25 raspberrypi homebridge[1100]:     ^
Dec 18 08:28:25 raspberrypi homebridge[1100]: Error: Attempting to register a platform 'homebridge-platform-blink-security.BlinkSecurityPlatform' which has already been registered!
Dec 18 08:28:25 raspberrypi homebridge[1100]:     at API.registerPlatform (/usr/local/lib/node_modules/homebridge/lib/api.js:150:11)
Dec 18 08:28:25 raspberrypi homebridge[1100]:     at Plugin.module.exports [as initializer] (/usr/local/lib/node_modules/homebridge-platform-blink-security/index.js:28:16)
Dec 18 08:28:25 raspberrypi homebridge[1100]:     at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:171:14)
Dec 18 08:28:25 raspberrypi homebridge[1100]:     at Array.forEach (<anonymous>)
Dec 18 08:28:25 raspberrypi homebridge[1100]:     at Server._loadPlugins (/usr/local/lib/node_modules/homebridge/lib/server.js:145:22)
Dec 18 08:28:25 raspberrypi homebridge[1100]:     at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:57:24)
Dec 18 08:28:25 raspberrypi homebridge[1100]:     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:32:16)
Dec 18 08:28:25 raspberrypi homebridge[1100]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Dec 18 08:28:25 raspberrypi homebridge[1100]:     at Module._compile (internal/modules/cjs/loader.js:689:30)
Dec 18 08:28:25 raspberrypi homebridge[1100]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
Dec 18 08:28:25 raspberrypi homebridge[1100]:     at Module.load (internal/modules/cjs/loader.js:599:32)
Dec 18 08:28:25 raspberrypi homebridge[1100]:     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
Dec 18 08:28:25 raspberrypi homebridge[1100]:     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
Dec 18 08:28:25 raspberrypi homebridge[1100]:     at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
Dec 18 08:28:25 raspberrypi homebridge[1100]:     at startup (internal/bootstrap/node.js:283:19)
Dec 18 08:28:25 raspberrypi homebridge[1100]:     at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
Dec 18 08:28:25 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE


```

**Comment by bartdorsey** [comment]
Make sure you don't have homebridge-platform-blink-security in your package.json file or installed on your system globally. That was a fork of this plugin, this one is called homebridge-blinkcameras.

**Comment by mokrol** [comment]
Any recommendations on how to find out if I do? I just know enough to be dangerous. :-)

**Comment by mokrol** [comment]
Maybe a better question is, I have homebridge-platform-blink-security installed on my machine, should I delete this and reinstall? Will that correct the problem?

**Comment by mokrol** [comment]
@bartdorsey  - Never mind, I got it.
