### ISSUE TITLE
Authentication issue

### ISSUE THREAD

**Issue by mfduarte** [bartdorsey/homebridge-blinkcameras#60]
Hello - after getting the 2FA code via email, entering the code in the plugin settings, and restarting HomeBridge, I see the following errors in the log:

[10/18/2023, 9:52:27 AM] [Blink] getBlinkStatus()
[10/18/2023, 9:52:27 AM] [Blink] SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at CacheableResponse.json (/usr/local/lib/node_modules/homebridge-blink-for-home/node_modules/@adobe/fetch/src/fetch/cacheableResponse.js:93:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at BlinkAPI._request (/usr/local/lib/node_modules/homebridge-blink-for-home/src/blink-api.js:290:26)
    at BlinkAPI.get (/usr/local/lib/node_modules/homebridge-blink-for-home/src/blink-api.js:229:16)
    at BlinkAPI.getBlinkStatus (/usr/local/lib/node_modules/homebridge-blink-for-home/src/blink-api.js:1282:16)
    at anonymize (/usr/local/lib/node_modules/homebridge-blink-for-home/src/blink.js:469:25)
    at BlinkHAP.diagnosticDebug (/usr/local/lib/node_modules/homebridge-blink-for-home/src/blink.js:499:13)
    at HomebridgeBlink.setupBlink (/usr/local/lib/node_modules/homebridge-blink-for-home/src/homebridge/index.js:112:59)
    at HomebridgeBlink.init (/usr/local/lib/node_modules/homebridge-blink-for-home/src/homebridge/index.js:41:26)
[10/18/2023, 9:52:27 AM] [Blink] TypeError: Cannot read properties of undefined (reading 'replaceAll')
    at anonymize (/usr/local/lib/node_modules/homebridge-blink-for-home/src/blink.js:472:33)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at BlinkHAP.diagnosticDebug (/usr/local/lib/node_modules/homebridge-blink-for-home/src/blink.js:499:13)
    at HomebridgeBlink.setupBlink (/usr/local/lib/node_modules/homebridge-blink-for-home/src/homebridge/index.js:112:59)
    at HomebridgeBlink.init (/usr/local/lib/node_modules/homebridge-blink-for-home/src/homebridge/index.js:41:26)
[10/18/2023, 9:52:27 AM] [Blink] Error: Blink Authentication failed.
    at HomebridgeBlink.setupBlink (/usr/local/lib/node_modules/homebridge-blink-for-home/src/homebridge/index.js:116:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at HomebridgeBlink.init (/usr/local/lib/node_modules/homebridge-blink-for-home/src/homebridge/index.js:41:26)
[10/18/2023, 9:52:27 AM] [Blink] NOTE: Blink devices in HomeKit will not be responsive.

**Comment by mfduarte** [comment]
Wrong repository, apologies.
