### ISSUE TITLE
Cannot pull information

### ISSUE THREAD

**Issue by AndrewCL1966** [bartdorsey/homebridge-blinkcameras#9]
I seem to have an issue where although blinkcameras connects, authenticates and gets the cameras and systems, it does not get the status properly. all works in setting but I get the following:

[3/11/2020, 4:09:23 PM] [Blink System] Discovering Cameras
[3/11/2020, 4:09:23 PM] [Blink System] Inside Lock
[3/11/2020, 4:09:23 PM] [Blink System] BlinkException [Error]: Can't retrieve system summary
    at Request._callback (/usr/local/lib/node_modules/homebridge-blinkcameras/node_modules/node-blink-security/lib/blink.js:100:20)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-blinkcameras/node_modules/request/request.js:185:22)
    at Request.emit (events.js:321:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:321:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:427:28)
    at IncomingMessage.emit (events.js:333:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

after the initial:
[3/11/2020, 4:17:55 PM] [Blink System] [Outdoor System] Registering
[3/11/2020, 4:17:55 PM] [Blink System] [Outdoor System] Initialized
[3/11/2020, 4:17:55 PM] [Blink System] [Outdoor System] Loaded cached accessory
[3/11/2020, 4:17:55 PM] [Blink System] [Upstaris System] Registering
[3/11/2020, 4:17:55 PM] [Blink System] [Upstaris System] Initialized
[3/11/2020, 4:17:55 PM] [Blink System] [Upstaris System] Loaded cached accessory
[3/11/2020, 4:17:55 PM] [Blink System] [Downstairs System] Registering
[3/11/2020, 4:17:55 PM] [Blink System] [Downstairs System] Initialized
[3/11/2020, 4:17:55 PM] [Blink System] [Downstairs System] Loaded cached accessory
[3/11/2020, 4:17:55 PM] [Blink System] [Hall Camera] Registering
[3/11/2020, 4:17:55 PM] [Blink System] [Hall Camera] Initialized
[3/11/2020, 4:17:55 PM] [Blink System] [Hall Camera] Loaded cached accessory
[3/11/2020, 4:17:55 PM] [Blink System] [lounge Camera] Registering
[3/11/2020, 4:17:55 PM] [Blink System] [lounge Camera] Initialized
[3/11/2020, 4:17:55 PM] [Blink System] [lounge Camera] Loaded cached accessory
[3/11/2020, 4:17:55 PM] [Blink System] [Front door Camera] Registering
[3/11/2020, 4:17:55 PM] [Blink System] [Front door Camera] Initialized
[3/11/2020, 4:17:55 PM] [Blink System] [Front door Camera] Loaded cached accessory
[3/11/2020, 4:17:55 PM] [Blink System] [Office Camera] Registering
[3/11/2020, 4:17:55 PM] [Blink System] [Office Camera] Initialized
[3/11/2020, 4:17:55 PM] [Blink System] [Office Camera] Loaded cached accessory
[3/11/2020, 4:17:55 PM] [Blink System] [Kitchen Camera] Registering
[3/11/2020, 4:17:55 PM] [Blink System] [Kitchen Camera] Initialized
[3/11/2020, 4:17:55 PM] [Blink System] [Kitchen Camera] Loaded cached accessory
[3/11/2020, 4:17:55 PM] [Blink System] [lower Balcony Camera] Registering
[3/11/2020, 4:17:55 PM] [Blink System] [lower Balcony Camera] Initialized
[3/11/2020, 4:17:55 PM] [Blink System] [lower Balcony Camera] Loaded cached accessory
[3/11/2020, 4:17:55 PM] [Blink System] [Upper Balcony Camera] Registering
[3/11/2020, 4:17:55 PM] [Blink System] [Upper Balcony Camera] Initialized
[3/11/2020, 4:17:55 PM] [Blink System] [Upper Balcony Camera] Loaded cached accessory
[3/11/2020, 4:17:55 PM] [Blink System] [living room Camera] Registering
[3/11/2020, 4:17:55 PM] [Blink System] [living room Camera] Initialized
[3/11/2020, 4:17:55 PM] [Blink System] [living room Camera] Loaded cached accessory
[3/11/2020, 4:17:55 PM] [Blink System] [Bedroom Camera] Registering
[3/11/2020, 4:17:55 PM] [Blink System] [Bedroom Camera] Initialized
[3/11/2020, 4:17:55 PM] [Blink System] [Bedroom Camera] Loaded cached accessory
[3/11/2020, 4:17:55 PM] [Blink System] [stairs Camera] Registering
[3/11/2020, 4:17:55 PM] [Blink System] [stairs Camera] Initialized
[3/11/2020, 4:17:55 PM] [Blink System] [stairs Camera] Loaded cached accessory
[3/11/2020, 4:17:55 PM] [SoundTouch] Searching accessories...
[3/11/2020, 4:17:55 PM] [Blink System] Finished Launching
[3/11/2020, 4:17:55 PM] [Blink System] Discovering Cameras
[3/11/2020, 4:17:55 PM] [Blink System] Inside Lock

I don't know what inside lock means....

Andrew

**Comment by roboterm** [comment]
I m experiencing the same error:  
BlinkException [Error]: Can't retrieve system summary
    at Request._callback (/usr/local/lib/node_modules/homebridge-blinkcameras/node_modules/node-blink-security/lib/blink.js:100:20)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-blinkcameras/node_modules/request/request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:310:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-blinkcameras/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:416:28)
    at IncomingMessage.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by bartdorsey** [comment]
This is usually caused by not being able to authenticate with Blink. Make sure you are updated to homebridge 1.0 and the latest version of the plugin which adds 2 factor authentication support.

**Comment by bartdorsey** [comment]
Also tracking issues like this here: https://github.com/bartdorsey/homebridge-blinkcameras/issues/22
